"""Generate frontend/src/utils/offlineData.ts from the backend rule engine, so the on-device fallback can never drift
from the server's bands, templates and wording (nothing is transcribed by hand).

Run from the repo root:  python3 backend/tools/gen_offline_data.py
"""
import json, os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "backend"))
from app.utils.rules_classifier import _POSE_FEATURE_BANDS  # noqa: E402
from app.services.correction import BIOMECHANICAL_TEMPLATES, DEFAULT_CORRECTIONS, _ESCALATION  # noqa: E402

flat = {}
for pose, joints in BIOMECHANICAL_TEMPLATES.items():
    flat[pose] = {}
    for joint, spec in joints.items():
        assert set(spec) == {"issue_low"}, f"unexpected template keys for {pose}.{joint}: {set(spec)}"
        flat[pose][joint] = spec["issue_low"]
bands = {p: [[n, float(lo), float(hi)] for n, lo, hi in b] for p, b in _POSE_FEATURE_BANDS.items()}
esc = {str(k): v for k, v in _ESCALATION.items()}
dump = lambda o: json.dumps(o, ensure_ascii=False, indent=2)
out = f"""// AUTO-GENERATED by backend/tools/gen_offline_data.py from the backend rule engine. Do not edit by hand.
export const POSE_BANDS: {{ [pose: string]: [string, number, number][] }} = {dump(bands)};

export const TEMPLATES: {{ [pose: string]: {{ [joint: string]: {{ [lang: string]: string }} }} }} = {dump(flat)};

export const DEFAULT_CORRECTIONS: {{ [lang: string]: string }} = {dump(DEFAULT_CORRECTIONS)};

export const ESCALATION: {{ [tier: string]: {{ [lang: string]: string }} }} = {dump(esc)};
"""
dst = os.path.join(ROOT, "frontend", "src", "utils", "offlineData.ts")
open(dst, "w", encoding="utf-8").write(out)
print("wrote", dst, len(out), "bytes;", len(bands), "banded poses,", len(flat), "poses with templates")
