// AUTO-GENERATED by backend/tools/gen_offline_data.py from the backend rule engine. Do not edit by hand.
export const POSE_BANDS: { [pose: string]: [string, number, number][] } = {
  "mountain_pose": [
    [
      "hip_l",
      140.0,
      180.0
    ],
    [
      "hip_r",
      140.0,
      180.0
    ],
    [
      "knee_l",
      140.0,
      180.0
    ],
    [
      "knee_r",
      140.0,
      180.0
    ],
    [
      "shoulder_l",
      0.0,
      55.0
    ],
    [
      "shoulder_r",
      0.0,
      55.0
    ],
    [
      "trunk_l",
      65.0,
      180.0
    ],
    [
      "trunk_r",
      65.0,
      180.0
    ]
  ],
  "upward_salute": [
    [
      "hip_l",
      140.0,
      180.0
    ],
    [
      "hip_r",
      140.0,
      180.0
    ],
    [
      "knee_l",
      140.0,
      180.0
    ],
    [
      "knee_r",
      140.0,
      180.0
    ],
    [
      "shoulder_l",
      115.0,
      180.0
    ],
    [
      "shoulder_r",
      115.0,
      180.0
    ],
    [
      "trunk_l",
      65.0,
      180.0
    ],
    [
      "trunk_r",
      65.0,
      180.0
    ]
  ],
  "downward_dog": [
    [
      "hip_l",
      20.0,
      140.0
    ],
    [
      "hip_r",
      20.0,
      140.0
    ],
    [
      "knee_l",
      110.0,
      180.0
    ],
    [
      "knee_r",
      110.0,
      180.0
    ],
    [
      "shoulder_l",
      95.0,
      180.0
    ],
    [
      "shoulder_r",
      95.0,
      180.0
    ]
  ],
  "plank": [
    [
      "hip_l",
      140.0,
      180.0
    ],
    [
      "hip_r",
      140.0,
      180.0
    ],
    [
      "knee_l",
      140.0,
      180.0
    ],
    [
      "knee_r",
      140.0,
      180.0
    ],
    [
      "shoulder_l",
      60.0,
      110.0
    ],
    [
      "shoulder_r",
      60.0,
      110.0
    ]
  ],
  "cobra_pose": [
    [
      "hip_l",
      120.0,
      180.0
    ],
    [
      "hip_r",
      120.0,
      180.0
    ],
    [
      "knee_l",
      120.0,
      180.0
    ],
    [
      "knee_r",
      120.0,
      180.0
    ],
    [
      "shoulder_l",
      5.0,
      50.0
    ],
    [
      "shoulder_r",
      5.0,
      50.0
    ],
    [
      "neck",
      80.0,
      180.0
    ]
  ],
  "child_pose": [
    [
      "hip_l",
      0.0,
      90.0
    ],
    [
      "hip_r",
      0.0,
      90.0
    ],
    [
      "knee_l",
      0.0,
      90.0
    ],
    [
      "knee_r",
      0.0,
      90.0
    ],
    [
      "shoulder_l",
      85.0,
      180.0
    ],
    [
      "shoulder_r",
      85.0,
      180.0
    ]
  ],
  "seated_staff": [
    [
      "hip_l",
      60.0,
      120.0
    ],
    [
      "hip_r",
      60.0,
      120.0
    ],
    [
      "knee_l",
      135.0,
      180.0
    ],
    [
      "knee_r",
      135.0,
      180.0
    ],
    [
      "trunk_l",
      60.0,
      180.0
    ],
    [
      "trunk_r",
      60.0,
      180.0
    ]
  ],
  "seated_easy_pose": [
    [
      "hip_l",
      50.0,
      120.0
    ],
    [
      "hip_r",
      50.0,
      120.0
    ],
    [
      "knee_l",
      0.0,
      125.0
    ],
    [
      "knee_r",
      0.0,
      125.0
    ],
    [
      "trunk_l",
      60.0,
      180.0
    ],
    [
      "trunk_r",
      60.0,
      180.0
    ]
  ],
  "tree_pose": [],
  "warrior_1": [
    [
      "shoulder_l",
      110.0,
      180.0
    ],
    [
      "shoulder_r",
      110.0,
      180.0
    ]
  ],
  "warrior_2": [
    [
      "shoulder_l",
      65.0,
      125.0
    ],
    [
      "shoulder_r",
      65.0,
      125.0
    ]
  ],
  "lunge_pose": [],
  "standing_forward_fold": [
    [
      "hip_l",
      0.0,
      70.0
    ],
    [
      "hip_r",
      0.0,
      70.0
    ],
    [
      "knee_l",
      120.0,
      180.0
    ],
    [
      "knee_r",
      120.0,
      180.0
    ]
  ],
  "halfway_lift": [
    [
      "hip_l",
      70.0,
      115.0
    ],
    [
      "hip_r",
      70.0,
      115.0
    ],
    [
      "knee_l",
      130.0,
      180.0
    ],
    [
      "knee_r",
      130.0,
      180.0
    ]
  ],
  "chair_pose": [
    [
      "hip_l",
      75.0,
      140.0
    ],
    [
      "hip_r",
      75.0,
      140.0
    ],
    [
      "knee_l",
      75.0,
      140.0
    ],
    [
      "knee_r",
      75.0,
      140.0
    ],
    [
      "shoulder_l",
      95.0,
      180.0
    ],
    [
      "shoulder_r",
      95.0,
      180.0
    ]
  ],
  "table_top": [
    [
      "hip_l",
      60.0,
      125.0
    ],
    [
      "hip_r",
      60.0,
      125.0
    ],
    [
      "knee_l",
      60.0,
      125.0
    ],
    [
      "knee_r",
      60.0,
      125.0
    ],
    [
      "shoulder_l",
      60.0,
      125.0
    ],
    [
      "shoulder_r",
      60.0,
      125.0
    ]
  ],
  "standing_pose": [
    [
      "hip_l",
      140.0,
      180.0
    ],
    [
      "hip_r",
      140.0,
      180.0
    ],
    [
      "knee_l",
      140.0,
      180.0
    ],
    [
      "knee_r",
      140.0,
      180.0
    ]
  ],
  "triangle": [
    [
      "knee_l",
      130.0,
      180.0
    ],
    [
      "knee_r",
      130.0,
      180.0
    ],
    [
      "shoulder_l",
      55.0,
      180.0
    ]
  ],
  "corpse": [
    [
      "hip_l",
      140.0,
      180.0
    ],
    [
      "hip_r",
      140.0,
      180.0
    ],
    [
      "knee_l",
      140.0,
      180.0
    ],
    [
      "knee_r",
      140.0,
      180.0
    ],
    [
      "shoulder_l",
      0.0,
      60.0
    ],
    [
      "shoulder_r",
      0.0,
      60.0
    ]
  ]
};

export const TEMPLATES: { [pose: string]: { [joint: string]: { [lang: string]: string } } } = {
  "warrior_2": {
    "knee_l": {
      "en": "Bend your left knee more to bring it directly over your ankle.",
      "hi": "अपने बाएं घुटने को थोड़ा और मोड़ें ताकि वह टखने के ठीक ऊपर रहे।",
      "bn": "আপনার বাম হাঁটু আরও বাঁকুন যাতে এটি গোড়ালির ঠিক উপরে থাকে।"
    },
    "knee_r": {
      "en": "Bend your right knee more to align it directly over your ankle.",
      "hi": "अपने दाएं घुटने को थोड़ा और मोड़ें ताकि वह टखने के ठीक ऊपर रहे।",
      "bn": "আপনার ডান হাঁটু আরও বাঁকুন যাতে এটি গোড়ালির ঠিক উপরে থাকে।"
    }
  },
  "chair_pose": {
    "knee_l": {
      "en": "Sit deeper to bring your thighs closer to parallel to the floor.",
      "hi": "जांघों को फर्श के समानांतर लाने के लिए थोड़ा नीचे बैठें।",
      "bn": "উরু মেঝের সমান্তরাল করার জন্য আর একটু নিচে বসুন।"
    },
    "knee_r": {
      "en": "Sit deeper to align both thighs towards parallel to the floor.",
      "hi": "दोनों जांघों को फर्श के समानांतर करने के लिए थोड़ा नीचे बैठें।",
      "bn": "দুই উরু মেঝের সমান্তরাল করার জন্য আর একটু নিচে বসুন।"
    }
  },
  "cobra_pose": {
    "neck": {
      "en": "Elongate your neck and gaze forward, relaxing your shoulders.",
      "hi": "अपनी गर्दन को लंबी करें और सामने की ओर देखें, कंधों को ढीला छोड़ें।",
      "bn": "আপনার ঘাড় সোজা করুন এবং সামনের দিকে তাকান, কাঁধ শিথিল রাখুন।"
    }
  },
  "plank": {
    "elbow_l": {
      "en": "Extend your left elbow to keep your arm straight.",
      "hi": "अपने बाएं हाथ को सीधा रखने के लिए अपनी बाईं कोहनी को फैलाएं।",
      "bn": "আপনার বাম হাত সোজা রাখতে বাম কনুই প্রসারিত করুন।"
    },
    "elbow_r": {
      "en": "Extend your right elbow to keep your arm straight.",
      "hi": "अपने दाएं हाथ को सीधा रखने के लिए अपनी दाईं कोहनी को फैलाएं।",
      "bn": "আপনার ডান হাত সোজা রাখতে ডান কনুই প্রসারিত করুন।"
    },
    "trunk_l": {
      "en": "Keep your spine and body in a straight line, do not let your hips sag.",
      "hi": "अपनी रीढ़ और शरीर को एक सीधी रेखा में रखें, अपने कूल्हों को नीचे न झुकने दें।",
      "bn": "আপনার মেরুদণ্ড এবং শরীর সোজা রাখুন, কোমর ঝুলে যেতে দেবেন না।"
    }
  },
  "tree_pose": {
    "knee_l": {
      "en": "Bend your left knee more and place your foot on your inner thigh.",
      "hi": "अपने बाएं घुटने को अधिक मोड़ें और अपने पैर को जांघ के अंदरूनी हिस्से पर रखें।",
      "bn": "আপনার বাম হাঁটু আরও বাঁকুন এবং পায়ের পাতাটি উরুর ভেতরের দিকে রাখুন।"
    },
    "hip_abduct_l": {
      "en": "Open your left hip outward to bring your knee to the side.",
      "hi": "अपने बाएं कूल्हे को बाहर की ओर खोलें ताकि आपका घुटना बगल की ओर हो सके।",
      "bn": "আপনার বাম হাঁটু পাশের দিকে আনতে বাম হিপ বাইরের দিকে প্রসারিত করুন।"
    },
    "knee_r": {
      "en": "Keep your standing right leg fully straight and strong.",
      "hi": "अपने खड़े हुए दाएं पैर को पूरी तरह से सीधा और मजबूत रखें।",
      "bn": "দাঁড়িয়ে থাকা ডান পা সম্পূর্ণ সোজা এবং শক্ত রাখুন।"
    }
  },
  "mountain_pose": {
    "knee_l": {
      "en": "Keep your left leg straight and engage your thigh muscles.",
      "hi": "अपने बाएं पैर को सीधा रखें और अपनी जांघ की मांसपेशियों को सक्रिय करें।",
      "bn": "আপনার বাম পা সোজা রাখুন এবং উরুর পেশী সক্রিয় করুন।"
    },
    "knee_r": {
      "en": "Keep your right leg straight and engage your thigh muscles.",
      "hi": "अपने दाएं पैर को सीधा रखें और अपनी जांघ की मांसपेशियों को सक्रिय करें।",
      "bn": "আপনার ডান পা সোজা রাখুন এবং উরুর পেশী সক্রিয় করুন।"
    },
    "trunk_l": {
      "en": "Lengthen your spine and stand tall with shoulders relaxed.",
      "hi": "अपनी रीढ़ को लंबा करें और कंधों को आराम देते हुए सीधे खड़े हों।",
      "bn": "মেরুদণ্ড লম্বা করে সোজা হয়ে দাঁড়ান এবং কাঁধ শিথিল রাখুন।"
    }
  },
  "downward_dog": {
    "hip_l": {
      "en": "Lift your hips higher to form a taller inverted V shape.",
      "hi": "अपने कूल्हों को ऊंचा उठाएं ताकि एक बड़ा उल्टा वी आकार बने।",
      "bn": "একটি বড় উল্টানো ভি আকৃতি তৈরি করতে আপনার কোমর আরও উঁচু করুন।"
    },
    "knee_l": {
      "en": "Straighten your legs as much as comfortable, keeping heels reaching down.",
      "hi": "जितना आरामदायक हो अपने पैरों को सीधा करें, एड़ियों को नीचे की ओर ले जाते हुए।",
      "bn": "যতটা আরামদায়ক পা সোজা করুন, গোড়ালি নিচের দিকে রাখুন।"
    },
    "shoulder_l": {
      "en": "Press firmly through your hands and extend your arms fully.",
      "hi": "अपने हाथों से मजबूती से दबाएं और अपनी बाहों को पूरी तरह फैलाएं।",
      "bn": "হাতের উপর দৃঢ়ভাবে চাপ দিন এবং বাহু সম্পূর্ণ প্রসারিত করুন।"
    }
  }
};

export const DEFAULT_CORRECTIONS: { [lang: string]: string } = {
  "en": "Maintain your posture, breathing steadily.",
  "hi": "अपना आसन बनाए रखें, साँस सहज रूप से लेते रहें।",
  "bn": "আপনার ভঙ্গি বজায় রাখুন, স্বাভাবিকভাবে শ্বাস নিতে থাকুন।"
};

export const ESCALATION: { [tier: string]: { [lang: string]: string } } = {
  "1": {
    "en": "{base} You're about {deg} degrees off.",
    "hi": "{base} आप लक्ष्य से लगभग {deg} डिग्री दूर हैं।",
    "bn": "{base} আপনি লক্ষ্য থেকে প্রায় {deg} ডিগ্রি দূরে আছেন।"
  },
  "2": {
    "en": "Ease out of the shape and reset. Come back only as far as feels comfortable today.",
    "hi": "आसन से धीरे-धीरे बाहर आएँ और फिर से शुरू करें। आज जितना सहज लगे, उतना ही करें।",
    "bn": "ভঙ্গি থেকে ধীরে বেরিয়ে আসুন এবং আবার শুরু করুন। আজ যতটা স্বচ্ছন্দ, ততটুকুই করুন।"
  }
};
