"""Build references_gen.tex (IEEE-style thebibliography) from references.bib, numbered in order of first \\cite in the section files.
IEEEtran.bst is not installed on this machine, so this replaces bibtex; references.bib (all fields verified online) stays the single source."""
import re, sys
bib = open("references.bib").read()
entries = {}
for m in re.finditer(r"@(\w+)\{([^,]+),(.*?)\n\}\n", bib, re.S):
    kind, key, body = m.group(1), m.group(2).strip(), m.group(3)
    f = {}
    for fm in re.finditer(r"\n\s*(\w+)\s*=\s*\{(.*?)\}\s*,?\s*(?=\n\s*\w+\s*=|\Z)", body + "\n", re.S):
        f[fm.group(1).lower()] = re.sub(r"\s+", " ", fm.group(2).strip())
    entries[key] = (kind.lower(), f)
order = []
main = open("asanaai_ieee_paper.tex").read()
files = [m.group(1) + ".tex" for m in re.finditer(r"\\input\{(sections/[^}]+)\}", main)]
text = "".join(open(f).read() for f in files)
for m in re.finditer(r"\\cite\{([^}]+)\}", text):
    for k in m.group(1).split(","):
        k = k.strip()
        if k not in order: order.append(k)
missing = [k for k in order if k not in entries]
assert not missing, f"cited but not in references.bib: {missing}"
def esc(s): return s.replace("_", "\\_").replace("&", "\\&").replace("%", "\\%").replace("#", "\\#")
def strip(s):  # drop case-protecting braces, keep accent macros
    s = s.replace("{\\'e}", "\u00e9").replace("{\\c{c}}", "\u00e7")
    return s.replace("{", "").replace("}", "")
def initials(first):
    out = []
    for tok in first.split():
        if "-" in tok and not tok.endswith("."):
            out.append("-".join(p[0] + "." for p in tok.split("-") if p))
        elif tok.endswith(".") and len(tok) <= 3: out.append(tok)
        else: out.append(tok[0] + ".")
    return " ".join(out)
def names(a):
    if a.startswith("{"): return strip(a)
    ps = [p.strip() for p in re.split(r"\s+and\s+", a)]
    fm = []
    for p in ps:
        t = p.split()
        fm.append(strip(t[-1]) if len(t) == 1 else initials(" ".join(t[:-1])) + " " + strip(t[-1]))
    if len(fm) > 6: return fm[0] + " \\textit{et al.}"
    return fm[0] if len(fm) == 1 else (" and ".join(fm) if len(fm) == 2 else ", ".join(fm[:-1]) + ", and " + fm[-1])
def render(kind, f):
    au = names(f["author"]); ti = '``' + strip(f["title"]) + ",'' "; yr = f.get("year", "")
    pp = f.get("pages", "")
    art = pp[:1] == "e" or (kind == "article" and f.get("journal") == "Patterns")   # article numbers, not page ranges
    pp_label = ("Art. no.~" if art else "pp.~") + pp
    if kind == "article":
        s = f"{au}, {ti}\\textit{{{strip(f['journal'])}}}"
        if "volume" in f: s += f", vol.~{f['volume']}"
        if "number" in f: s += f", no.~{f['number']}"
        s += f", {yr}"
        if pp: s += f", {pp_label}"
        if "doi" in f: s += f", doi: {f['doi']}"
        return s + "."
    if kind == "inproceedings":
        s = f"{au}, {ti}in \\textit{{{strip(f['booktitle'])}}}"
        if f.get("series"): s += f", {f['series']}"
        if "volume" in f and f.get("series"): s += f", vol.~{f['volume']}"
        elif "volume" in f: s += f", vol.~{f['volume']}"
        if "number" in f: s += f", no.~{f['number']}"
        s += f", {yr}"
        if pp: s += f", {pp_label}"
        if "note" in f: s += f", {f['note']}"
        if "doi" in f: s += f", doi: {f['doi']}"
        return s + "."
    s = f"{au}, {ti}"
    if "howpublished" in f: s += f"{strip(f['howpublished'])}, "
    if not ("howpublished" in f and yr in f["howpublished"]): s += yr
    else: s = s.rstrip(", ")
    return s + "."
out = ["% generated by make_refs.py from references.bib -- do not edit by hand", "\\begin{thebibliography}{%d}" % len(order)]
for k in order:
    kind, f = entries[k]; out.append(f"\\bibitem{{{k}}} {esc(render(kind, f)).replace(chr(92)+chr(92)+'textit', chr(92)+'textit')}")
out.append("\\end{thebibliography}")
open("references_gen.tex", "w").write("\n".join(out) + "\n"); print(len(order), "references,", "unused in text:", [k for k in entries if k not in order])
